//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ots_protocol.proto
namespace Aliyun.OpenServices.OpenTableService.ProtoBuf
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ColumnSchema")]
    public partial class ColumnSchema : global::ProtoBuf.IExtensible
    {
        public ColumnSchema() { }

        private string _name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string name
        {
            get { return _name; }
            set { _name = value; }
        }
        private Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnType _type;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnType type
        {
            get { return _type; }
            set { _type = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ColumnValue")]
    public partial class ColumnValue : global::ProtoBuf.IExtensible
    {
        public ColumnValue() { }

        private Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnType _type;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnType type
        {
            get { return _type; }
            set { _type = value; }
        }
        private long? _value_i = long.MinValue;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"value_i", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        //[global::System.ComponentModel.DefaultValue(long.MinValue)]
        public long? value_i
        {
            get { return _value_i; }
            set { _value_i = value; }
        }
        private string _value_s = "";
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"value_s", DataFormat = global::ProtoBuf.DataFormat.Default)]
        //[global::System.ComponentModel.DefaultValue("")]
        public string value_s
        {
            get { return _value_s; }
            set { _value_s = value; }
        }
        private bool? _value_b = default(bool);
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"value_b", DataFormat = global::ProtoBuf.DataFormat.Default)]
        //[global::System.ComponentModel.DefaultValue(default(bool))]
        public bool? value_b
        {
            get { return _value_b; }
            set { _value_b = value; }
        }
        private double? _value_d = default(double);
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"value_d", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        //[global::System.ComponentModel.DefaultValue(default(double))]
        public double? value_d
        {
            get { return _value_d; }
            set { _value_d = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Column")]
    public partial class Column : global::ProtoBuf.IExtensible
    {
        public Column() { }

        private string _name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string name
        {
            get { return _name; }
            set { _name = value; }
        }
        private Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnValue _value;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnValue value
        {
            get { return _value; }
            set { _value = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Row")]
    public partial class Row : global::ProtoBuf.IExtensible
    {
        public Row() { }

        private global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Column> _primary_keys = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Column>();
        [global::ProtoBuf.ProtoMember(1, Name = @"primary_keys", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Column> primary_keys
        {
            get { return _primary_keys; }
            set { this._primary_keys = value; }
        }

        private global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Column> _columns = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Column>();
        [global::ProtoBuf.ProtoMember(2, Name = @"columns", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Column> columns
        {
            get { return _columns; }
            set { this._columns = value; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"RowPutChange")]
    public partial class RowPutChange : global::ProtoBuf.IExtensible
    {
        public RowPutChange() { }

        private Aliyun.OpenServices.OpenTableService.ProtoBuf.Row _row;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"row", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.Row row
        {
            get { return _row; }
            set { _row = value; }
        }
        private Aliyun.OpenServices.OpenTableService.ProtoBuf.RowPutChange.CheckingType _checking_type;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"checking_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.RowPutChange.CheckingType checking_type
        {
            get { return _checking_type; }
            set { _checking_type = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"CheckingType")]
        public enum CheckingType
        {

            [global::ProtoBuf.ProtoEnum(Name = @"NO",
                Value = 0)]
            NO = 0,

            [global::ProtoBuf.ProtoEnum(Name = @"UPDATE", Value = 1)]
            UPDATE = 1,

            [global::ProtoBuf.ProtoEnum(Name = @"INSERT", Value = 2)]
            INSERT = 2
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"RowDeleteChange")]
    public partial class RowDeleteChange : global::ProtoBuf.IExtensible
    {
        public RowDeleteChange() { }

        private global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Column> _primary_keys = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Column>();
        [global::ProtoBuf.ProtoMember(1, Name = @"primary_keys", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Column> primary_keys
        {
            get { return _primary_keys; }
            set { this._primary_keys = value; }
        }

        private readonly global::System.Collections.Generic.List<string> _column_names = new global::System.Collections.Generic.List<string>();
        [global::ProtoBuf.ProtoMember(2, Name = @"column_names", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<string> column_names
        {
            get { return _column_names; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ViewMeta")]
    public partial class ViewMeta : global::ProtoBuf.IExtensible
    {
        public ViewMeta() { }

        private string _view_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"view_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string view_name
        {
            get { return _view_name; }
            set { _view_name = value; }
        }
        private global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnSchema> _primary_keys = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnSchema>();
        [global::ProtoBuf.ProtoMember(2, Name = @"primary_keys", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnSchema> primary_keys
        {
            get { return _primary_keys; }
            set { this._primary_keys = value; }
        }

        private global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnSchema> _columns = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnSchema>();
        [global::ProtoBuf.ProtoMember(3, Name = @"columns", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnSchema> columns
        {
            get { return _columns; }
            set { this._columns = value; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"TableMeta")]
    public partial class TableMeta : global::ProtoBuf.IExtensible
    {
        public TableMeta() { }

        private string _table_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"table_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string table_name
        {
            get { return _table_name; }
            set { _table_name = value; }
        }
        private global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ViewMeta> _views = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ViewMeta>();
        [global::ProtoBuf.ProtoMember(2, Name = @"views", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ViewMeta> views
        {
            get { return _views; }
            set { this._views = value; }
        }

        private global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnSchema> _primary_keys = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnSchema>();
        [global::ProtoBuf.ProtoMember(3, Name = @"primary_keys", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnSchema> primary_keys
        {
            get { return _primary_keys; }
            set { _primary_keys = value; }
        }

        private string _table_group_name = "";
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"table_group_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string table_group_name
        {
            get { return _table_group_name; }
            set { _table_group_name = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"GetRowParameter")]
    public partial class GetRowParameter : global::ProtoBuf.IExtensible
    {
        public GetRowParameter() { }

        private string _table_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"table_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string table_name
        {
            get { return _table_name; }
            set { _table_name = value; }
        }
        private global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Column> _primary_keys = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Column>();
        [global::ProtoBuf.ProtoMember(2, Name = @"primary_keys", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Column> primary_keys
        {
            get { return _primary_keys; }
            set { this._primary_keys = value; }
        }

        private global::System.Collections.Generic.List<string> _column_names = new global::System.Collections.Generic.List<string>();
        [global::ProtoBuf.ProtoMember(3, Name = @"column_names", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<string> column_names
        {
            get { return _column_names; }
            set { this._column_names = value; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PutRowParameter")]
    public partial class PutRowParameter : global::ProtoBuf.IExtensible
    {
        public PutRowParameter() { }

        private string _table_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"table_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string table_name
        {
            get { return _table_name; }
            set { _table_name = value; }
        }
        private Aliyun.OpenServices.OpenTableService.ProtoBuf.RowPutChange _row_change;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"row_change", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.RowPutChange row_change
        {
            get { return _row_change; }
            set { _row_change = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"DeleteRowParameter")]
    public partial class DeleteRowParameter : global::ProtoBuf.IExtensible
    {
        public DeleteRowParameter() { }

        private string _table_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"table_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string table_name
        {
            get { return _table_name; }
            set { _table_name = value; }
        }
        private Aliyun.OpenServices.OpenTableService.ProtoBuf.RowDeleteChange _row_change;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"row_change", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.RowDeleteChange row_change
        {
            get { return _row_change; }
            set { _row_change = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ErrorMessage")]
    public partial class ErrorMessage : global::ProtoBuf.IExtensible
    {
        public ErrorMessage() { }

        private string _code;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string code
        {
            get { return _code; }
            set { _code = value; }
        }
        private string _message = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string message
        {
            get { return _message; }
            set { _message = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CreateTableGroupRequest")]
    public partial class CreateTableGroupRequest : global::ProtoBuf.IExtensible
    {
        public CreateTableGroupRequest() { }

        private string _table_group_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"table_group_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string table_group_name
        {
            get { return _table_group_name; }
            set { _table_group_name = value; }
        }
        private Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnType _partition_key_type;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"partition_key_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnType partition_key_type
        {
            get { return _partition_key_type; }
            set { _partition_key_type = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"DeleteTableGroupRequest")]
    public partial class DeleteTableGroupRequest : global::ProtoBuf.IExtensible
    {
        public DeleteTableGroupRequest() { }

        private string _table_group_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"table_group_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string table_group_name
        {
            get { return _table_group_name; }
            set { _table_group_name = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ListTableGroupResponse")]
    public partial class ListTableGroupResponse : global::ProtoBuf.IExtensible
    {
        public ListTableGroupResponse() { }

        private readonly global::System.Collections.Generic.List<string> _table_group_names = new global::System.Collections.Generic.List<string>();
        [global::ProtoBuf.ProtoMember(1, Name = @"table_group_names", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<string> table_group_names
        {
            get { return _table_group_names; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CreateTableRequest")]
    public partial class CreateTableRequest : global::ProtoBuf.IExtensible
    {
        public CreateTableRequest() { }

        private Aliyun.OpenServices.OpenTableService.ProtoBuf.TableMeta _table_meta;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"table_meta", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.TableMeta table_meta
        {
            get { return _table_meta; }
            set { _table_meta = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ListTableResponse")]
    public partial class ListTableResponse : global::ProtoBuf.IExtensible
    {
        public ListTableResponse() { }

        private readonly global::System.Collections.Generic.List<string> _table_names = new global::System.Collections.Generic.List<string>();
        [global::ProtoBuf.ProtoMember(1, Name = @"table_names", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<string> table_names
        {
            get { return _table_names; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"GetTableMetaRequest")]
    public partial class GetTableMetaRequest : global::ProtoBuf.IExtensible
    {
        public GetTableMetaRequest() { }

        private string _table_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"table_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string table_name
        {
            get { return _table_name; }
            set { _table_name = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"GetTableMetaResponse")]
    public partial class GetTableMetaResponse : global::ProtoBuf.IExtensible
    {
        public GetTableMetaResponse() { }

        private Aliyun.OpenServices.OpenTableService.ProtoBuf.TableMeta _table_meta;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"table_meta", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.TableMeta table_meta
        {
            get { return _table_meta; }
            set { _table_meta = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"DeleteTableRequest")]
    public partial class DeleteTableRequest : global::ProtoBuf.IExtensible
    {
        public DeleteTableRequest() { }

        private string _table_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"table_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string table_name
        {
            get { return _table_name; }
            set { _table_name = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StartTransactionRequest")]
    public partial class StartTransactionRequest : global::ProtoBuf.IExtensible
    {
        public StartTransactionRequest() { }

        private string _entity_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"entity_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string entity_name
        {
            get { return _entity_name; }
            set { _entity_name = value; }
        }
        private Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnValue _partition_key_value;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"partition_key_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnValue partition_key_value
        {
            get { return _partition_key_value; }
            set { _partition_key_value = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"StartTransactionResponse")]
    public partial class StartTransactionResponse : global::ProtoBuf.IExtensible
    {
        public StartTransactionResponse() { }

        private string _transaction_id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"transaction_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string transaction_id
        {
            get { return _transaction_id; }
            set { _transaction_id = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"AbortTransactionRequest")]
    public partial class AbortTransactionRequest : global::ProtoBuf.IExtensible
    {
        public AbortTransactionRequest() { }

        private string _transaction_id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"transaction_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string transaction_id
        {
            get { return _transaction_id; }
            set { _transaction_id = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CommitTransactionRequest")]
    public partial class CommitTransactionRequest : global::ProtoBuf.IExtensible
    {
        public CommitTransactionRequest() { }

        private string _transaction_id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"transaction_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string transaction_id
        {
            get { return _transaction_id; }
            set { _transaction_id = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"GetRowRequest")]
    public partial class GetRowRequest : global::ProtoBuf.IExtensible
    {
        public GetRowRequest() { }

        private Aliyun.OpenServices.OpenTableService.ProtoBuf.GetRowParameter _get_row_parameter;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"get_row_parameter", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.GetRowParameter get_row_parameter
        {
            get { return _get_row_parameter; }
            set { _get_row_parameter = value; }
        }
        private string _transaction_id = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"transaction_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string transaction_id
        {
            get { return _transaction_id; }
            set { _transaction_id = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"GetRowResponse")]
    public partial class GetRowResponse : global::ProtoBuf.IExtensible
    {
        public GetRowResponse() { }

        private string _table_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"table_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string table_name
        {
            get { return _table_name; }
            set { _table_name = value; }
        }
        private Aliyun.OpenServices.OpenTableService.ProtoBuf.Row _row;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"row", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.Row row
        {
            get { return _row; }
            set { _row = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"GetRowsByRangeRequest")]
    public partial class GetRowsByRangeRequest : global::ProtoBuf.IExtensible
    {
        public GetRowsByRangeRequest() { }

        private string _table_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"table_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string table_name
        {
            get { return _table_name; }
            set { _table_name = value; }
        }
        private global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Column> _primary_key_prefix = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Column>();
        [global::ProtoBuf.ProtoMember(2, Name = @"primary_key_prefix", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Column> primary_key_prefix
        {
            get { return _primary_key_prefix; }
            set { _primary_key_prefix = value; }
        }

        private string _range_key_name;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"range_key_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string range_key_name
        {
            get { return _range_key_name; }
            set { _range_key_name = value; }
        }
        private Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnValue _range_begin;
        [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"range_begin", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnValue range_begin
        {
            get { return _range_begin; }
            set { _range_begin = value; }
        }
        private Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnValue _range_end;
        [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name = @"range_end", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.ColumnValue range_end
        {
            get { return _range_end; }
            set { _range_end = value; }
        }
        private global::System.Collections.Generic.List<string> _column_names = new global::System.Collections.Generic.List<string>();
        [global::ProtoBuf.ProtoMember(6, Name = @"column_names", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<string> column_names
        {
            get { return _column_names; }
            set { _column_names = value; }
        }

        private bool _is_reverse;
        [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name = @"is_reverse", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public bool is_reverse
        {
            get { return _is_reverse; }
            set { _is_reverse = value; }
        }
        private uint _limit = default(uint);
        [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(uint))]
        public uint limit
        {
            get { return _limit; }
            set { _limit = value; }
        }
        private string _next_token = "";
        [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name = @"next_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string next_token
        {
            get { return _next_token; }
            set { _next_token = value; }
        }
        private string _transaction_id = "";
        [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name = @"transaction_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string transaction_id
        {
            get { return _transaction_id; }
            set { _transaction_id = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"GetRowsByRangeResponse")]
    public partial class GetRowsByRangeResponse : global::ProtoBuf.IExtensible
    {
        public GetRowsByRangeResponse() { }

        private string _table_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"table_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string table_name
        {
            get { return _table_name; }
            set { _table_name = value; }
        }
        private readonly global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Row> _rows = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Row>();
        [global::ProtoBuf.ProtoMember(2, Name = @"rows", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.Row> rows
        {
            get { return _rows; }
        }

        private string _next_token = "";
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"next_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string next_token
        {
            get { return _next_token; }
            set { _next_token = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PutRowRequest")]
    public partial class PutRowRequest : global::ProtoBuf.IExtensible
    {
        public PutRowRequest() { }

        private Aliyun.OpenServices.OpenTableService.ProtoBuf.PutRowParameter _put_row_parameter;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"put_row_parameter", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.PutRowParameter put_row_parameter
        {
            get { return _put_row_parameter; }
            set { _put_row_parameter = value; }
        }
        private string _transaction_id = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"transaction_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string transaction_id
        {
            get { return _transaction_id; }
            set { _transaction_id = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"DeleteRowRequest")]
    public partial class DeleteRowRequest : global::ProtoBuf.IExtensible
    {
        public DeleteRowRequest() { }

        private Aliyun.OpenServices.OpenTableService.ProtoBuf.DeleteRowParameter _delete_row_parameter;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"delete_row_parameter", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.DeleteRowParameter delete_row_parameter
        {
            get { return _delete_row_parameter; }
            set { _delete_row_parameter = value; }
        }
        private string _transaction_id = "";
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"transaction_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string transaction_id
        {
            get { return _transaction_id; }
            set { _transaction_id = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ModifyItem")]
    public partial class ModifyItem : global::ProtoBuf.IExtensible
    {
        public ModifyItem() { }

        private Aliyun.OpenServices.OpenTableService.ProtoBuf.ModifyItem.ModifyType _type;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.ModifyItem.ModifyType type
        {
            get { return _type; }
            set { _type = value; }
        }
        private Aliyun.OpenServices.OpenTableService.ProtoBuf.RowPutChange _row_put_change = null;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"row_put_change", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.RowPutChange row_put_change
        {
            get { return _row_put_change; }
            set { _row_put_change = value; }
        }
        private Aliyun.OpenServices.OpenTableService.ProtoBuf.RowDeleteChange _row_delete_change = null;
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"row_delete_change", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.RowDeleteChange row_delete_change
        {
            get { return _row_delete_change; }
            set { _row_delete_change = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ModifyType")]
        public enum ModifyType
        {

            [global::ProtoBuf.ProtoEnum(Name = @"PUT", Value = 0)]
            PUT = 0,

            [global::ProtoBuf.ProtoEnum(Name = @"DELETE", Value = 1)]
            DELETE = 1
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"BatchModifyRowRequest")]
    public partial class BatchModifyRowRequest : global::ProtoBuf.IExtensible
    {
        public BatchModifyRowRequest() { }

        private string _table_name;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"table_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string table_name
        {
            get { return _table_name; }
            set { _table_name = value; }
        }
        private global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ModifyItem> _modify_items = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ModifyItem>();
        [global::ProtoBuf.ProtoMember(2, Name = @"modify_items", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ModifyItem> modify_items
        {
            get { return _modify_items; }
            set { this._modify_items = value; }
        }

        private string _transaction_id;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"transaction_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string transaction_id
        {
            get { return _transaction_id; }
            set { _transaction_id = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"MultiGetRowRequest")]
    public partial class MultiGetRowRequest : global::ProtoBuf.IExtensible
    {
        public MultiGetRowRequest() { }

        private readonly global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.GetRowParameter> _parameters = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.GetRowParameter>();
        [global::ProtoBuf.ProtoMember(1, Name = @"parameters", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.GetRowParameter> parameters
        {
            get { return _parameters; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"MultiGetRowResponseItem")]
    public partial class MultiGetRowResponseItem : global::ProtoBuf.IExtensible
    {
        public MultiGetRowResponseItem() { }

        private bool _is_succeed;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"is_succeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public bool is_succeed
        {
            get { return _is_succeed; }
            set { _is_succeed = value; }
        }
        private Aliyun.OpenServices.OpenTableService.ProtoBuf.ErrorMessage _error = null;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.ErrorMessage error
        {
            get { return _error; }
            set { _error = value; }
        }
        private string _table_name = "";
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"table_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string table_name
        {
            get { return _table_name; }
            set { _table_name = value; }
        }
        private Aliyun.OpenServices.OpenTableService.ProtoBuf.Row _row = null;
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"row", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public Aliyun.OpenServices.OpenTableService.ProtoBuf.Row row
        {
            get { return _row; }
            set { _row = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"MultiGetRowResponse")]
    public partial class MultiGetRowResponse : global::ProtoBuf.IExtensible
    {
        public MultiGetRowResponse() { }

        private readonly global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.MultiGetRowResponseItem> _items = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.MultiGetRowResponseItem>();
        [global::ProtoBuf.ProtoMember(1, Name = @"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.MultiGetRowResponseItem> items
        {
            get { return _items; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"MultiPutRowRequest")]
    public partial class MultiPutRowRequest : global::ProtoBuf.IExtensible
    {
        public MultiPutRowRequest() { }

        private readonly global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.PutRowParameter> _parameters = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.PutRowParameter>();
        [global::ProtoBuf.ProtoMember(1, Name = @"parameters", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.PutRowParameter> parameters
        {
            get { return _parameters; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"MultiPutRowResponse")]
    public partial class MultiPutRowResponse : global::ProtoBuf.IExtensible
    {
        public MultiPutRowResponse() { }

        private readonly global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ErrorMessage> _messages = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ErrorMessage>();
        [global::ProtoBuf.ProtoMember(1, Name = @"messages", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ErrorMessage> messages
        {
            get { return _messages; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"MultiDeleteRowRequest")]
    public partial class MultiDeleteRowRequest : global::ProtoBuf.IExtensible
    {
        public MultiDeleteRowRequest() { }

        private readonly global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.DeleteRowParameter> _parameters = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.DeleteRowParameter>();
        [global::ProtoBuf.ProtoMember(1, Name = @"parameters", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.DeleteRowParameter> parameters
        {
            get { return _parameters; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"MultiDeleteRowResponse")]
    public partial class MultiDeleteRowResponse : global::ProtoBuf.IExtensible
    {
        public MultiDeleteRowResponse() { }

        private readonly global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ErrorMessage> _messages = new global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ErrorMessage>();
        [global::ProtoBuf.ProtoMember(1, Name = @"messages", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Aliyun.OpenServices.OpenTableService.ProtoBuf.ErrorMessage> messages
        {
            get { return _messages; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::ProtoBuf.ProtoContract(Name = @"ColumnType")]
    public enum ColumnType
    {

        [global::ProtoBuf.ProtoEnum(Name = @"INF_MIN", Value = 0)]
        INF_MIN = 0,

        [global::ProtoBuf.ProtoEnum(Name = @"INF_MAX", Value = 1)]
        INF_MAX = 1,

        [global::ProtoBuf.ProtoEnum(Name = @"INTEGER", Value = 2)]
        INTEGER = 2,

        [global::ProtoBuf.ProtoEnum(Name = @"STRING", Value = 3)]
        STRING = 3,

        [global::ProtoBuf.ProtoEnum(Name = @"BOOLEAN", Value = 4)]
        BOOLEAN = 4,

        [global::ProtoBuf.ProtoEnum(Name = @"DOUBLE", Value = 5)]
        DOUBLE = 5
    }

}