//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aliyun.OpenServices.OpenTableService {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OtsExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OtsExceptions() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aliyun.OpenServices.OpenTableService.OtsExceptions", typeof(OtsExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 不能将Double.NaN转换为ColumnValue类型的对象，OTS不支持值为NaN的Double值，请避免使用。 的本地化字符串。
        /// </summary>
        internal static string CannotCastDoubleNaN {
            get {
                return ResourceManager.GetString("CannotCastDoubleNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解码返回结果中列的值时出现错误。 的本地化字符串。
        /// </summary>
        internal static string ColumnValueCannotBeDecoded {
            get {
                return ResourceManager.GetString("ColumnValueCannotBeDecoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持终结点给定的协议。仅支持HTTP协议，即终结点必须以&quot;http://&quot;开头。 的本地化字符串。
        /// </summary>
        internal static string EndpointNotSupportedProtocal {
            get {
                return ResourceManager.GetString("EndpointNotSupportedProtocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定分页键的值无效。该值必须为0，或小于表（Table）结构或视图（View）中定义的主键个数的正数。 的本地化字符串。
        /// </summary>
        internal static string InvalidPagingKeyLength {
            get {
                return ResourceManager.GetString("InvalidPagingKeyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RequestID: {0}, HostID: {1}。 的本地化字符串。
        /// </summary>
        internal static string InvalidResponseMessage {
            get {
                return ResourceManager.GetString("InvalidResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表（Table）、表组（Table Group）、视图（View）、主键（Primary Key）或列（Column）的名称无效。OTS中名称必须由数字、英文字母或下划线组成，其中英文字母大小写敏感，数字不能作为第一个字符，名称的总长度不能超过100个字符。 的本地化字符串。
        /// </summary>
        internal static string NameFormatIsInvalid {
            get {
                return ResourceManager.GetString("NameFormatIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要至少给定一个主键（Primary Key）。 的本地化字符串。
        /// </summary>
        internal static string NoPrimaryKeySpecified {
            get {
                return ResourceManager.GetString("NoPrimaryKeySpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rowChanges中至少需要包含一行数据。 的本地化字符串。
        /// </summary>
        internal static string NoRowForBatchModifyData {
            get {
                return ResourceManager.GetString("NoRowForBatchModifyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求失败，原因： {0}；OTS错误代码: {1}。 的本地化字符串。
        /// </summary>
        internal static string OpenTableServiceExceptionMessageFormat {
            get {
                return ResourceManager.GetString("OpenTableServiceExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求的返回结果验证失败，原因：{0}。 的本地化字符串。
        /// </summary>
        internal static string OpenTableServiceInvalidResponseMessageFormat {
            get {
                return ResourceManager.GetString("OpenTableServiceInvalidResponseMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当正向读取时，PrimaryKeyRange.InfMin和PrimaryKeyRange.InfMax只能依次应用于PrimaryKeyRange.RangeBegin和PrimaryKeyRange.RangeEnd。当反向读取时，PrimaryKeyRange.InfMin和PrimaryKeyRange.InfMax只能依次应用于PrimaryKeyRange.RangeEnd和PrimaryKeyRange.RangeBegin。 的本地化字符串。
        /// </summary>
        internal static string PKInfNotAllowed {
            get {
                return ResourceManager.GetString("PKInfNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主键（Primary Key）的值无效，不能为空引用或值为长度是零的字符串。 的本地化字符串。
        /// </summary>
        internal static string PrimaryKeyValueIsNullOrEmpty {
            get {
                return ResourceManager.GetString("PrimaryKeyValueIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须显式地给定Top属性的值，且必须大于或等于0。 的本地化字符串。
        /// </summary>
        internal static string QueryTopValueNotSet {
            get {
                return ResourceManager.GetString("QueryTopValueNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值必须大于或等于零。 的本地化字符串。
        /// </summary>
        internal static string QueryTopValueOutOfRange {
            get {
                return ResourceManager.GetString("QueryTopValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当正向读取时，主键范围的起始值需要小于或等于结束值。当反向读取时，主键范围的起始值需要大于或等于结束值。整型按数字大小比较；字符型按字典顺序比较；布尔型的false小于true；任何类型的值均大于PrimaryKeyRange.InfMin且小于PrimaryKeyRange.InfMax。 的本地化字符串。
        /// </summary>
        internal static string RangeBeginGreaterThanRangeEnd {
            get {
                return ResourceManager.GetString("RangeBeginGreaterThanRangeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主键范围的没有设置，请先设置Range属性。 的本地化字符串。
        /// </summary>
        internal static string RangeNotSet {
            get {
                return ResourceManager.GetString("RangeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rangeBegin和rangeEnd的数据类型必须与给定主键的数据类型相匹配。 的本地化字符串。
        /// </summary>
        internal static string RangeTypeNotMatch {
            get {
                return ResourceManager.GetString("RangeTypeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回结果数据不完整。 的本地化字符串。
        /// </summary>
        internal static string ResponseDataIncomplete {
            get {
                return ResourceManager.GetString("ResponseDataIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回结果缺失头“{0}”。 的本地化字符串。
        /// </summary>
        internal static string ResponseDoesNotContainHeader {
            get {
                return ResourceManager.GetString("ResponseDoesNotContainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回结果超时。 的本地化字符串。
        /// </summary>
        internal static string ResponseExpired {
            get {
                return ResourceManager.GetString("ResponseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回验证失败。 的本地化字符串。
        /// </summary>
        internal static string ResponseFailedAuthorization {
            get {
                return ResourceManager.GetString("ResponseFailedAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此版本的SDK只支持Base64格式的数据编码。请考虑升级SDK以支持编码{0}。 的本地化字符串。
        /// </summary>
        internal static string UnsupportedEncodingFormat {
            get {
                return ResourceManager.GetString("UnsupportedEncodingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析失败，无法将值转换转换为{0}类型。 的本地化字符串。
        /// </summary>
        internal static string ValueCastFailedFormat {
            get {
                return ResourceManager.GetString("ValueCastFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值的数据类型不是{0}。 的本地化字符串。
        /// </summary>
        internal static string ValueCastInvalidTypeFormat {
            get {
                return ResourceManager.GetString("ValueCastInvalidTypeFormat", resourceCulture);
            }
        }
    }
}
