//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schneider.REM.Common.Resource.zh_CN {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schneider.REM.Common.Resource.zh_CN.DB", typeof(DB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供冷面积.
        /// </summary>
        internal static string AdvancedProperty_CoolingArea {
            get {
                return ResourceManager.GetString("AdvancedProperty_CoolingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采暖面积.
        /// </summary>
        internal static string AdvancedProperty_HeatingArea {
            get {
                return ResourceManager.GetString("AdvancedProperty_HeatingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总面积.
        /// </summary>
        internal static string AdvancedProperty_TotalArea {
            get {
                return ResourceManager.GetString("AdvancedProperty_TotalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总人口.
        /// </summary>
        internal static string AdvancedProperty_TotalPopulation {
            get {
                return ResourceManager.GetString("AdvancedProperty_TotalPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空气.
        /// </summary>
        internal static string Commodity_AirQuality {
            get {
                return ResourceManager.GetString("Commodity_AirQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 煤.
        /// </summary>
        internal static string Commodity_Coal {
            get {
                return ResourceManager.GetString("Commodity_Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 煤油.
        /// </summary>
        internal static string Commodity_CoalOil {
            get {
                return ResourceManager.GetString("Commodity_CoalOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冷量.
        /// </summary>
        internal static string Commodity_CoolQ {
            get {
                return ResourceManager.GetString("Commodity_CoolQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 柴油.
        /// </summary>
        internal static string Commodity_DieselOil {
            get {
                return ResourceManager.GetString("Commodity_DieselOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电.
        /// </summary>
        internal static string Commodity_Electricity {
            get {
                return ResourceManager.GetString("Commodity_Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天然气.
        /// </summary>
        internal static string Commodity_Gas {
            get {
                return ResourceManager.GetString("Commodity_Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 热量.
        /// </summary>
        internal static string Commodity_HeatQ {
            get {
                return ResourceManager.GetString("Commodity_HeatQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 低压蒸汽.
        /// </summary>
        internal static string Commodity_LowPressureSteam {
            get {
                return ResourceManager.GetString("Commodity_LowPressureSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他.
        /// </summary>
        internal static string Commodity_Other {
            get {
                return ResourceManager.GetString("Commodity_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 汽油.
        /// </summary>
        internal static string Commodity_Petrol {
            get {
                return ResourceManager.GetString("Commodity_Petrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软水.
        /// </summary>
        internal static string Commodity_SoftWater {
            get {
                return ResourceManager.GetString("Commodity_SoftWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自来水.
        /// </summary>
        internal static string Commodity_Water {
            get {
                return ResourceManager.GetString("Commodity_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 机场.
        /// </summary>
        internal static string Industry_Airport {
            get {
                return ResourceManager.GetString("Industry_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全行业.
        /// </summary>
        internal static string Industry_All_Industries {
            get {
                return ResourceManager.GetString("Industry_All Industries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服装零售.
        /// </summary>
        internal static string Industry_Clothing_retail {
            get {
                return ResourceManager.GetString("Industry_Clothing retail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据中心.
        /// </summary>
        internal static string Industry_Data_Center {
            get {
                return ResourceManager.GetString("Industry_Data Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 医院.
        /// </summary>
        internal static string Industry_Hospital {
            get {
                return ResourceManager.GetString("Industry_Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 酒店.
        /// </summary>
        internal static string Industry_Hotel {
            get {
                return ResourceManager.GetString("Industry_Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 酒店（五星级）.
        /// </summary>
        internal static string Industry_Hotel__Five_stat_ {
            get {
                return ResourceManager.GetString("Industry_Hotel (Five-stat)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 酒店（四星级）.
        /// </summary>
        internal static string Industry_Hotel__Four_star_ {
            get {
                return ResourceManager.GetString("Industry_Hotel (Four-star)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 酒店（三星级）.
        /// </summary>
        internal static string Industry_Hotel__Three_stat_ {
            get {
                return ResourceManager.GetString("Industry_Hotel (Three-stat)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 酒店（二星级及以下）.
        /// </summary>
        internal static string Industry_Hotel__Two_star_and_below_ {
            get {
                return ResourceManager.GetString("Industry_Hotel (Two-star and below)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商场.
        /// </summary>
        internal static string Industry_Mall {
            get {
                return ResourceManager.GetString("Industry_Mall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制造业.
        /// </summary>
        internal static string Industry_Manufacturing {
            get {
                return ResourceManager.GetString("Industry_Manufacturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 办公建筑.
        /// </summary>
        internal static string Industry_Office_Building {
            get {
                return ResourceManager.GetString("Industry_Office Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轨道交通.
        /// </summary>
        internal static string Industry_Rail_Transit {
            get {
                return ResourceManager.GetString("Industry_Rail Transit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 零售业.
        /// </summary>
        internal static string Industry_Retail {
            get {
                return ResourceManager.GetString("Industry_Retail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学校.
        /// </summary>
        internal static string Industry_School {
            get {
                return ResourceManager.GetString("Industry_School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超市.
        /// </summary>
        internal static string Industry_Supermarket {
            get {
                return ResourceManager.GetString("Industry_Supermarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通讯.
        /// </summary>
        internal static string Industry_Telecommunication {
            get {
                return ResourceManager.GetString("Industry_Telecommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通讯基站.
        /// </summary>
        internal static string Industry_Telecommunication_base_station {
            get {
                return ResourceManager.GetString("Industry_Telecommunication base station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通讯营业厅.
        /// </summary>
        internal static string Industry_Telecommunication_business_hall {
            get {
                return ResourceManager.GetString("Industry_Telecommunication business hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 机房.
        /// </summary>
        internal static string Industry_Telecommunication_workshop {
            get {
                return ResourceManager.GetString("Industry_Telecommunication workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空调箱.
        /// </summary>
        internal static string SystemDimensionTemplateItem_AHU {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_AHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 风冷冷水机组.
        /// </summary>
        internal static string SystemDimensionTemplateItem_AirCooledCoolingMachine {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_AirCooledCoolingMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空气净化器.
        /// </summary>
        internal static string SystemDimensionTemplateItem_AirPurifier {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_AirPurifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空调末端.
        /// </summary>
        internal static string SystemDimensionTemplateItem_AirTerminal {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_AirTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 锅炉.
        /// </summary>
        internal static string SystemDimensionTemplateItem_Boiler {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_Boiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 厨房餐厅.
        /// </summary>
        internal static string SystemDimensionTemplateItem_Canteen {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_Canteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冷冻换热泵.
        /// </summary>
        internal static string SystemDimensionTemplateItem_ChilledHeatWaterPump {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_ChilledHeatWaterPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冷冻/换热泵.
        /// </summary>
        internal static string SystemDimensionTemplateItem_ChilledOrHeatWaterPump {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_ChilledOrHeatWaterPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冷冻泵.
        /// </summary>
        internal static string SystemDimensionTemplateItem_ChilledWaterPump {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_ChilledWaterPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 厨房炊事设备.
        /// </summary>
        internal static string SystemDimensionTemplateItem_CookingAppliances {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_CookingAppliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冷热源.
        /// </summary>
        internal static string SystemDimensionTemplateItem_CoolingHeatingSource {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_CoolingHeatingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供冷主机.
        /// </summary>
        internal static string SystemDimensionTemplateItem_CoolingMachine {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_CoolingMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冷热兼供主机.
        /// </summary>
        internal static string SystemDimensionTemplateItem_CoolingOrHeatingMachine {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_CoolingOrHeatingMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冷却塔风机.
        /// </summary>
        internal static string SystemDimensionTemplateItem_CoolingTower {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_CoolingTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冷却泵.
        /// </summary>
        internal static string SystemDimensionTemplateItem_CoolingWaterPump {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_CoolingWaterPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT机.
        /// </summary>
        internal static string SystemDimensionTemplateItem_CTMachine {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_CTMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 污梯.
        /// </summary>
        internal static string SystemDimensionTemplateItem_DebrisElevator {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_DebrisElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分散空调.
        /// </summary>
        internal static string SystemDimensionTemplateItem_DecentralizedAirConditioning {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_DecentralizedAirConditioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 血透.
        /// </summary>
        internal static string SystemDimensionTemplateItem_Dialyzer {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_Dialyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生活水泵.
        /// </summary>
        internal static string SystemDimensionTemplateItem_DomesticWaterPump {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_DomesticWaterPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 给排水泵.
        /// </summary>
        internal static string SystemDimensionTemplateItem_DrainagePump {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_DrainagePump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电采暖设备.
        /// </summary>
        internal static string SystemDimensionTemplateItem_ElectricHeating {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_ElectricHeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 功能区域用电.
        /// </summary>
        internal static string SystemDimensionTemplateItem_ElectricityComsumptionInFunctionArea {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_ElectricityComsumptionInFunctionArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 辅助区域用电.
        /// </summary>
        internal static string SystemDimensionTemplateItem_ElectricityComsumptionInSecondZone {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_ElectricityComsumptionInSecondZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游泳池用电.
        /// </summary>
        internal static string SystemDimensionTemplateItem_ElectricitySwimmingPool {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_ElectricitySwimmingPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电梯.
        /// </summary>
        internal static string SystemDimensionTemplateItem_Elevator {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_Elevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排风机.
        /// </summary>
        internal static string SystemDimensionTemplateItem_ExhausteFan {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_ExhausteFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新风机.
        /// </summary>
        internal static string SystemDimensionTemplateItem_FAHU {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_FAHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 风机盘管.
        /// </summary>
        internal static string SystemDimensionTemplateItem_FCU {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_FCU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 货梯.
        /// </summary>
        internal static string SystemDimensionTemplateItem_FreightElevator {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_FreightElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车库照明.
        /// </summary>
        internal static string SystemDimensionTemplateItem_GarageLighting {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_GarageLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供热主机.
        /// </summary>
        internal static string SystemDimensionTemplateItem_HeatingMachine {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_HeatingMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 换热泵.
        /// </summary>
        internal static string SystemDimensionTemplateItem_HeatWaterPump {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_HeatWaterPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空调.
        /// </summary>
        internal static string SystemDimensionTemplateItem_HVAC {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_HVAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 厨房空调机.
        /// </summary>
        internal static string SystemDimensionTemplateItem_HVACCooking {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_HVACCooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息设备专用空调.
        /// </summary>
        internal static string SystemDimensionTemplateItem_HVACEquipment {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_HVACEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高压氧舱.
        /// </summary>
        internal static string SystemDimensionTemplateItem_HyperbaricOxygenChamber {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_HyperbaricOxygenChamber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICU病房.
        /// </summary>
        internal static string SystemDimensionTemplateItem_ICU {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_ICU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息设备.
        /// </summary>
        internal static string SystemDimensionTemplateItem_InformationEquipment {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_InformationEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息机房.
        /// </summary>
        internal static string SystemDimensionTemplateItem_InformationRoom {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_InformationRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关键.
        /// </summary>
        internal static string SystemDimensionTemplateItem_KeySystem {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_KeySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 洗衣房设备.
        /// </summary>
        internal static string SystemDimensionTemplateItem_LaundryEquipment {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_LaundryEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 照明.
        /// </summary>
        internal static string SystemDimensionTemplateItem_Lighting {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 溶液除湿机组.
        /// </summary>
        internal static string SystemDimensionTemplateItem_LiquidDesiccantAirCondition {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_LiquidDesiccantAirCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大堂.
        /// </summary>
        internal static string SystemDimensionTemplateItem_Lobby {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜景照明.
        /// </summary>
        internal static string SystemDimensionTemplateItem_NightSceneLighting {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_NightSceneLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 核磁共振.
        /// </summary>
        internal static string SystemDimensionTemplateItem_NMR {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_NMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他.
        /// </summary>
        internal static string SystemDimensionTemplateItem_Other {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插座.
        /// </summary>
        internal static string SystemDimensionTemplateItem_Outlet {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_Outlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 厨房照明插座.
        /// </summary>
        internal static string SystemDimensionTemplateItem_OutletLighting {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_OutletLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外包商户.
        /// </summary>
        internal static string SystemDimensionTemplateItem_OutsourceingClient {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_OutsourceingClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外包餐厅.
        /// </summary>
        internal static string SystemDimensionTemplateItem_OutsourcingCanteen {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_OutsourcingCanteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客梯.
        /// </summary>
        internal static string SystemDimensionTemplateItem_PassengerElevator {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_PassengerElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动力.
        /// </summary>
        internal static string SystemDimensionTemplateItem_PowerSystem {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_PowerSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精密空调.
        /// </summary>
        internal static string SystemDimensionTemplateItem_PrecisionAirConditioner {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_PrecisionAirConditioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公共照明.
        /// </summary>
        internal static string SystemDimensionTemplateItem_PublicLighting {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_PublicLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中水泵.
        /// </summary>
        internal static string SystemDimensionTemplateItem_RecycledWaterPump {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_RecycledWaterPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交换机.
        /// </summary>
        internal static string SystemDimensionTemplateItem_Router {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_Router", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器.
        /// </summary>
        internal static string SystemDimensionTemplateItem_Server {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务部门.
        /// </summary>
        internal static string SystemDimensionTemplateItem_Service {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务部门照明.
        /// </summary>
        internal static string SystemDimensionTemplateItem_ServiceLight {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_ServiceLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务部门插座.
        /// </summary>
        internal static string SystemDimensionTemplateItem_ServiceOutlet {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_ServiceOutlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排污泵.
        /// </summary>
        internal static string SystemDimensionTemplateItem_SewagePump {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_SewagePump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 厨房排烟机.
        /// </summary>
        internal static string SystemDimensionTemplateItem_SmokeExhaustMachine {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_SmokeExhaustMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特殊.
        /// </summary>
        internal static string SystemDimensionTemplateItem_Special {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扶梯.
        /// </summary>
        internal static string SystemDimensionTemplateItem_Staircase {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_Staircase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 潜水泵.
        /// </summary>
        internal static string SystemDimensionTemplateItem_SubmersiblePump {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_SubmersiblePump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 末端再热.
        /// </summary>
        internal static string SystemDimensionTemplateItem_TerminalReheat {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_TerminalReheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发射机.
        /// </summary>
        internal static string SystemDimensionTemplateItem_Transmitter {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_Transmitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPS损耗.
        /// </summary>
        internal static string SystemDimensionTemplateItem_UPSLoss {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_UPSLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRV空调.
        /// </summary>
        internal static string SystemDimensionTemplateItem_VRV {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_VRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 热水器.
        /// </summary>
        internal static string SystemDimensionTemplateItem_WaterHeater {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_WaterHeater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X光机.
        /// </summary>
        internal static string SystemDimensionTemplateItem_XMachine {
            get {
                return ResourceManager.GetString("SystemDimensionTemplateItem_XMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安培.
        /// </summary>
        internal static string Uom_AMPS {
            get {
                return ResourceManager.GetString("Uom_AMPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 千焦.
        /// </summary>
        internal static string Uom_GJ {
            get {
                return ResourceManager.GetString("Uom_GJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小时.
        /// </summary>
        internal static string Uom_h {
            get {
                return ResourceManager.GetString("Uom_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 焦.
        /// </summary>
        internal static string Uom_J {
            get {
                return ResourceManager.GetString("Uom_J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 千克.
        /// </summary>
        internal static string Uom_kg {
            get {
                return ResourceManager.GetString("Uom_kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 千克标煤.
        /// </summary>
        internal static string Uom_kgce {
            get {
                return ResourceManager.GetString("Uom_kgce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 千伏安.
        /// </summary>
        internal static string Uom_KVA {
            get {
                return ResourceManager.GetString("Uom_KVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 千伏安时.
        /// </summary>
        internal static string Uom_KVAH {
            get {
                return ResourceManager.GetString("Uom_KVAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 千乏.
        /// </summary>
        internal static string Uom_KVAR {
            get {
                return ResourceManager.GetString("Uom_KVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 千乏时.
        /// </summary>
        internal static string Uom_KVARH {
            get {
                return ResourceManager.GetString("Uom_KVARH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 千瓦.
        /// </summary>
        internal static string Uom_KW {
            get {
                return ResourceManager.GetString("Uom_KW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 千瓦时.
        /// </summary>
        internal static string Uom_KWH {
            get {
                return ResourceManager.GetString("Uom_KWH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分.
        /// </summary>
        internal static string Uom_m {
            get {
                return ResourceManager.GetString("Uom_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无.
        /// </summary>
        internal static string Uom_null {
            get {
                return ResourceManager.GetString("Uom_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 百分比.
        /// </summary>
        internal static string Uom_Percentage {
            get {
                return ResourceManager.GetString("Uom_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人.
        /// </summary>
        internal static string Uom_Person {
            get {
                return ResourceManager.GetString("Uom_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 百万分比浓度.
        /// </summary>
        internal static string Uom_ppm {
            get {
                return ResourceManager.GetString("Uom_ppm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人民币.
        /// </summary>
        internal static string Uom_RMB {
            get {
                return ResourceManager.GetString("Uom_RMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒.
        /// </summary>
        internal static string Uom_s {
            get {
                return ResourceManager.GetString("Uom_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吨.
        /// </summary>
        internal static string Uom_Ton {
            get {
                return ResourceManager.GetString("Uom_Ton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 棵树.
        /// </summary>
        internal static string Uom_Tree {
            get {
                return ResourceManager.GetString("Uom_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伏特.
        /// </summary>
        internal static string Uom_VOLTS {
            get {
                return ResourceManager.GetString("Uom_VOLTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部区域.
        /// </summary>
        internal static string Zone_All_Zones {
            get {
                return ResourceManager.GetString("Zone_All Zones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 寒冷地区.
        /// </summary>
        internal static string Zone_Cold_Region {
            get {
                return ResourceManager.GetString("Zone_Cold Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 严寒地区A区.
        /// </summary>
        internal static string Zone_Extreme_Cold_Region_A {
            get {
                return ResourceManager.GetString("Zone_Extreme Cold Region A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 严寒地区B区.
        /// </summary>
        internal static string Zone_Extreme_Cold_Region_B {
            get {
                return ResourceManager.GetString("Zone_Extreme Cold Region B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夏热冬冷地区.
        /// </summary>
        internal static string Zone_Hot_Summer_and_Cold_Winter_Region {
            get {
                return ResourceManager.GetString("Zone_Hot Summer and Cold Winter Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夏热冬暖地区.
        /// </summary>
        internal static string Zone_Subtropical_Region {
            get {
                return ResourceManager.GetString("Zone_Subtropical Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 温和地区.
        /// </summary>
        internal static string Zone_Temperate_Region {
            get {
                return ResourceManager.GetString("Zone_Temperate Region", resourceCulture);
            }
        }
    }
}
